# -*- coding: utf-8 -*-
"""calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A0gKNO-TZlSU0ZrQwTFfk5ATbdCFWL4v
"""

def calculator():
  while True:
    print("add")
    print("sub")
    print("multiply")
    print("div")
    print("mod")
    print("return")

    operations = input("enter your operations: ")
    if operations == 'return':
      print("end")
      break

    value1 = float(input("enter first number: "))
    value2 = float(input("enter second number: "))

    if operations == 'add':
      result = value1+value2
      operation = "+"

    elif  operations == 'sub':
      result = value1-value2
      operation = "-"

    elif operations == 'multiply':
      result = value1*value2
      operation = "*"

    elif operations == 'div':
      result = value1/value2
      operation = "/"

    elif operations == 'mod':
      result = value1%value2
      operation = "%"

    else:
      print("false")
      continue

    print(f"{value1} {operation} {value2} = {result}")

    response = input("Do youwant to perform another calculation (y/n): ")
    if response.lower() != 'y':
        print("end")
        break


if __name__ == "__main__":
    calculator()